const AMENITY_STATUS_ACTIVE = "Active";
const AMENITY_STATUS_INACTIVE = "Inactive";

const AMENITY_TYPE_WHOLE_DAY = "Full Day";
const AMENITY_TYPE_FREE = "Free Booking";
const AMENITY_TYPE_HALF_DAY = "Half Day";
const AMENITY_TYPE_HOURLY = "Hourly";

const TIME_SLOT_MORNING = "Morning";
const TIME_SLOT_AFTERNOON = "Afternoon";

export {
  AMENITY_STATUS_ACTIVE,
  AMENITY_STATUS_INACTIVE,
  AMENITY_TYPE_HALF_DAY,
  AMENITY_TYPE_HOURLY,
  AMENITY_TYPE_WHOLE_DAY,
  TIME_SLOT_AFTERNOON,
  TIME_SLOT_MORNING,
  AMENITY_TYPE_FREE,
};
