const EXPENSE_TYPE_DYNAMIC = "dynamic";
const EXPENSE_TYPE_STATIC = "static";
const EXPENSE_TYPE_AMC = "amc";

const ASSOCIATION_PAYMENT_ACCOUNT = "Account";
const ASSOCIATION_PAYMENT_PETTY_CASH = "Petty Cash";
const ASSOCIATION_PAYMENT_CASH = "Cash";

const PETTY_CASH = "pettyCash";
const ACCOUNT_BALANCE = "accountBalance";

const ASSOCIATION_TYPE_EXPENSE = "expense";
const ASSOCIATION_TYPE_CREDIT = "credit";

const FILTER_TYPE_MONTH = "monthRange";
const FILTER_TYPE_DATE = "dateRange";

export {
  EXPENSE_TYPE_DYNAMIC, 
  EXPENSE_TYPE_STATIC,
  EXPENSE_TYPE_AMC,
  ASSOCIATION_PAYMENT_PETTY_CASH,
  ASSOCIATION_PAYMENT_ACCOUNT,
  ASSOCIATION_PAYMENT_CASH,
  ASSOCIATION_TYPE_EXPENSE,
  ASSOCIATION_TYPE_CREDIT,
  ACCOUNT_BALANCE,
  PETTY_CASH,
  FILTER_TYPE_DATE,
  FILTER_TYPE_MONTH,
};
