const MC_TYPE_MC_MEMBER = "MC Member";
const MC_TYPE_EC_MEMBER = "EC Member";
const MC_TYPE_COMMUNITY_REPRESENTATIVE = "Community Respresentative";

const MC_LOGIN_AS_MC = "mc";
const MC_LOGIN_AS_EC = "ec";
const MC_LOGIN_AS_COMMUNITY = "community";


export { MC_TYPE_COMMUNITY_REPRESENTATIVE, MC_TYPE_EC_MEMBER, MC_TYPE_MC_MEMBER, MC_LOGIN_AS_COMMUNITY, MC_LOGIN_AS_EC, MC_LOGIN_AS_MC }