// types
const NOTIFICATION_PAYMENT_DUES_TYPES = "Payment Dues Types";
const NOTIFICATION_PAYMENT_REMINDER_TYPES = "Payment Reminder Type";
const NOTIFICATION_ASSOCIATION_MEETING = "Association Meeting";

const NOTIFICATION_EMAIL_TYPE_ONE_TIME = "One Time";
const NOTIFICATION_EMAIL_TYPE_RECURRING = "Recurring";

const NOTIFICATION_TO_ADMIN = "Admin";
const NOTIFICATION_TO_MC_EC = "MC/EC";
const NOTIFICATION_TO_IFM = "Ifm";
const NOTIFICATION_TO_ALL_MEMBER = "All Members";
const NOTIFICATION_TO_ALL_OWNER = "All Owners";
const NOTIFICATION_TO_SPECIFIC = "Specific";

const RECURRING_TYPE_DAILY = "Daily";
const RECURRING_TYPE_WEEKLY = "Weekly";
const RECURRING_TYPE_MONTHLY = "Monthly";

const NOTIFICATION_LIST_ACTIVE = "active";
const NOTIFICATION_LIST_EXPIRED = "expired";

export {
  NOTIFICATION_ASSOCIATION_MEETING,
  NOTIFICATION_PAYMENT_DUES_TYPES,
  NOTIFICATION_PAYMENT_REMINDER_TYPES,
  NOTIFICATION_TO_ADMIN,
  NOTIFICATION_TO_MC_EC,
  NOTIFICATION_TO_IFM,
  NOTIFICATION_TO_ALL_MEMBER,
  NOTIFICATION_TO_ALL_OWNER,
  NOTIFICATION_TO_SPECIFIC,
  NOTIFICATION_EMAIL_TYPE_ONE_TIME,
  NOTIFICATION_EMAIL_TYPE_RECURRING,
  RECURRING_TYPE_DAILY,
  RECURRING_TYPE_MONTHLY,
  RECURRING_TYPE_WEEKLY,
  NOTIFICATION_LIST_ACTIVE,
  NOTIFICATION_LIST_EXPIRED,
};
